version: 0.2

phases:
  build:
    commands:
      - cd ubuntu/standard/7.0
      - ECR_URL=948396734470.dkr.ecr.ap-southeast-2.amazonaws.com/cicd
      - IMAGE_NAME=codebuild
      - aws ecr get-login-password  | docker login --username AWS --password-stdin $ECR_URL$/IMAGE_NAME
      - docker build -t $IMAGE_NAME -f Dockerfile .
      - docker tag codebuild $ECR_URL/$IMAGE_NAME:latest
      - docker push $ECR_URL/$IMAGE_NAME:latest
